name: Push Daily Itinerary Notification

on:
  schedule:
    # 22:00 UTC = 07:00 JST (Japón)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  send-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install node-fetch@2 dotenv
      - name: Send daily itinerary notification
        env:
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
        run: node scripts/sendDailyItineraryNotification.js
