name: Test Push Notificación (15 Agosto 2025)

on:
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Enviar notificación de prueba (15 Agosto 2025)
        env:
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
        run: |
          node scripts/sendDailyItineraryNotification_TEST.js
